name: stare
description: Be the Better You.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rive: ^0.9.1
  provider: ^6.0.3
  flutter_svg: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rive/
    - assets/icons/
    - assets/images/moods/
    - assets/images/actions/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 200
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 800